services:
  katana:
    image: ghcr.io/casterlabs/katana:latest
    restart: always
    volumes:
      - ./config.json:/home/container/config.json
    ports:
      # - 81:81 # Management UI
      - 80:80
      - 443:443
