services:
  katana:
    image: ghcr.io/casterlabs/katana:latest
    restart: always
    volumes:
      - data:/home/container/data
    ports:
      # - 81:81 # Management UI
      - 80:80
      - 443:443

volumes:
  data: